server:
  port: 9081
spring:
  application:
    name: Bootstrap Spring Boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: P@ssw0rd
    url: jdbc:mysql://localhost:3306/sm_project?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true
  output:
    ansi:
      enabled: DETECT
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
