
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'APInvoice', 1, 1, 999999999, 1, N'APR', NULL, N'cDba-Ӧ����Ʊ��ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'ARInvoice', 1, 1, 999999999, 1, N'ARR', NULL, N'cDba-Ӧ�շ�Ʊ��ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'BusinessType', 1, 1, 999999999, 1, N'BUT', NULL, N'cDba-ҵ������ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'Config', 1, 1, 999999999, 1, N'CFG', NULL, N'cDba-����ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'Customer', 1, 1, 999999999, 1, N'CUR', NULL, N'cDba-�ͻ�ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'DeliveryNote', 1, 1, 999999999, 1, N'DNR', NULL, N'cDba-������ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'FinancingDemand', 1, 1, 999999999, 1, N'FDO', NULL, N'cDba-��������ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'GoodsReceipt', 1, 1, 999999999, 1, N'GRR', NULL, N'cDba-��ⵥID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'Member', 1, 1, 999999999, 1, N'USR', NULL, N'cDba-�û�ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'MessageTemplate', 1, 1, 999999999, 1, N'MGT', NULL, N'cDba-��Ϣģ��ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'Offering', 1, 1, 999999999, 1, N'OFR', NULL, N'cDba-��ƷID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'OfferingProvider', 1, 1, 999999999, 1, N'OPS', NULL, N'cDba-��Ʒģ��ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'OrderInquire', 1, 1, 999999999, 1, N'OIO', NULL, N'cDba-ѯ��/����ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'OrderOffering', 1, 1, 999999999, 1, N'OOR', NULL, N'cDba-����ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'OrderPurchase', 1, 1, 999999999, 1, N'OPO', NULL, N'cDba-�ɹ�����ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'Organization', 1, 1, 999999999, 1, N'ORG', NULL, N'cDba-��֯ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'PurchaseOrder', 1, 1, 999999999, 1, N'POR', NULL, N'cDba-�ɹ�����ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'SalesOrder', 1, 1, 999999999, 1, N'SOR', NULL, N'cDba-���۶���ID', N'2018-12-01')
INSERT [cDba].[cfg_SysSequence] ([SequenceName], [CurrentValue], [InitValue], [MaxValue], [StepValue], [PreFixString], [PostFixString], [Comments], [CurrDate]) VALUES (N'Supplier', 1, 1, 999999999, 1, N'SUP', NULL, N'cDba-��Ӧ��ID', N'2018-12-01')



