#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: 9082
spring:
  application:
    name: Bootstrap Spring Boot
  datasource:
    tomcat:
      initial-size: 20
      max-active: 300
      max-wait: 10000
      test-on-borrow: true
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1;databaseName=sm_project;
    username: sa
    password: P@ssw0rd
  jpa:
    show-sql: true
    hibernate:
      naming:
          #implicit-strategy: com.example.CustomNamingStrategy
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        hbm2ddl:
          auto: update
        multiTenancy: SCHEMA
        multi_tenant_connection_provider: com.example.multitenancy.MsSqlMultiTenantConnectionProviderImpl
        tenant_identifier_resolver: com.example.multitenancy.MultiTenantIdentifierResolver
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  output:
    ansi:
      enabled: DETECT
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
